name: vamshi
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: print my name
        run: |
            echo "my name is vamshi"
            echo "my name is balu"
            echo "my name is vishnu"
